name: Docker

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push Docker image to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ github.token }}
        repository: "${{ github.repository }}/dfw"
        cache_froms: "${{ github.repository }}/dfw"
        tag_with_ref: true
        always_pull: true
        add_git_labels: true
