name: Prepare release

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Retrieve cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          !target/gh-pages
        key: ${{ runner.os }}-cargo-ci-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: cargo build --release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
      env:
        TARGET: x86_64-unknown-linux-musl
    - name: Create checksum
      run: |
        sha256sum target/release/dfw > target/release/dfw.sha256

    - name: Identify if tag is a prerelease
      id: tag-prerelease
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "::set-output name=value::false"
        else
          echo "::set-output name=value::true"
        fi
    - name: Prepare release
      id: prepare-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: v${{ github.ref }}
        draft: true
        prerelease: ${{ steps.tag-prerelease.outputs.value }}

    - name: Upload static DFW binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.prepare-release.outputs.upload_url }}
        asset_path: target/release/dfw
        asset_name: dfw-x86_64-unknown-linux-musl
        asset_content_type: application/octet-stream
    - name: Upload static DFW binary checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.prepare-release.outputs.upload_url }}
        asset_path: target/release/dfw.sha256
        asset_name: dfw-x86_64-unknown-linux-musl.sha256
        asset_content_type: application/octet-stream
